Config = {}

Config.Items = {
    label = "Gun Dealer",
    slots = 5,
    items = {
		[1] = {
            name = "weapon_heavypistol",
            price = 10000,
            amount = 50,
			info = {},
            type = "item",
			slot = 1,
		},
		[2] = {
            name = "weapon_minismg",
            price = 15000,
            amount = 50,
			info = {},
            type = "item",
			slot = 2,
        },
        [3] = {
            name = "weapon_pistol",
            price = 6500,
            amount = 50,
			info = {},
            type = "item",
			slot = 3,
        },
        [4] = {
            name = "weapon_compactrifle",
            price = 17000,
            amount = 50,
			info = {},
            type = "item",
			slot = 4,
        },
        [5] = {
            name = "weapon_carbinerifle",
            price = 45000,
            amount = 50,
			info = {},
            type = "item",
			slot = 5,
        },
        [6] = {
            name = "weapon_specialcarbine",
            price = 45000,
            amount = 50,
			info = {},
            type = "item",
			slot = 6,
        },
        [7] = {
            name = "weapon_assaultrifle",
            price = 35000,
            amount = 50,
			info = {},
            type = "item",
			slot = 7,
        },
        [8] = {
            name = "weapon_appistol",
            price = 15000,
            amount = 50,
			info = {},
            type = "item",
			slot = 8,
        },
        [9] = {
            name = "weapon_microsmg2",
            price = 45000,
            amount = 50,
			info = {},
            type = "item",
			slot = 9,
        },
        [10] = {
            name = "weapon_microsmg3",
            price = 35000,
            amount = 50,
			info = {},
            type = "item",
			slot = 10,
        },
        [11] = {
            name = "rifle_ammo",
            price = 65000,
            amount = 50,
			info = {},
            type = "item",
			slot = 11,
        },
        [12] = {
            name = "pistol_ammo",
            price = 1000,
            amount = 50,
			info = {},
            type = "item",
			slot = 12,
        },
        [13] = {
            name = "weapon_advancedrifle",
            price = 65000,
            amount = 50,
			info = {},
            type = "item",
			slot = 13,
        },
        [14] = {
            name = "pistol_suppressor",
            price = 1000,
            amount = 50,
			info = {},
            type = "item",
			slot = 14,
        },
        [15] = {
            name = "pistol_extendedclip",
            price = 1000,
            amount = 50,
			info = {},
            type = "item",
			slot = 15,
        },
        [16] = {
            name = "pistol_flashlight",
            price = 1000,
            amount = 50,
			info = {},
            type = "item",
			slot = 16,
        },
        [17] = {
            name = "microsmg_extendedclip",
            price = 1500,
            amount = 50,
			info = {},
            type = "item",
			slot = 17,
        },
        [18] = {
            name = "microsmg_scope",
            price = 1500,
            amount = 50,
			info = {},
            type = "item",
			slot = 18,
        },
        [19] = {
            name = "pistol_suppressor",
            price = 1500,
            amount = 50,
			info = {},
            type = "item",
			slot = 19,
        },
        [20] = {
            name = "carbinerifle_scope",
            price = 2000,
            amount = 50,
			info = {},
            type = "item",
			slot = 20,
        },
        [21] = {
            name = "carbinerifle_scope",
            price = 2000,
            amount = 50,
			info = {},
            type = "item",
			slot = 21,
        },
        [22] = {
            name = "carbinerifle_extendedclip",
            price = 2000,
            amount = 50,
			info = {},
            type = "item",
			slot = 22,
        },
        [23] = {
            name = "rifle_suppressor",
            price = 2000,
            amount = 50,
			info = {},
            type = "item",
			slot = 23,
        },
        [24] = {
            name = "bag",
            price = 10000,
            amount = 50,
			info = {},
            type = "item",
			slot = 24,
        },
        [25] = {
            name = "weapon_smokegrenade",
            price = 45000,
            amount = 50,
			info = {},
            type = "item",
			slot = 25,
        },
        [26] = {
            name = "electronickit",
            price = 2000,
            amount = 50,
			info = {},
            type = "item",
			slot = 26,
        },
        [27] = {
            name = "trojan_usb",
            price = 2000,
            amount = 50,
			info = {},
            type = "item",
			slot = 27,
        },
        [28] = {
            name = "gasmask",
            price = 2500,
            amount = 50,
			info = {},
            type = "item",
			slot = 28,
        },
        [29] = {
            name = "heavyarmor",
            price = 2500,
            amount = 50,
			info = {},
            type = "item",
			slot = 29,
        },
        [30] = {
            name = "handcuffs",
            price = 550,
            amount = 50,
			info = {},
            type = "item",
			slot = 30,
        },
        [31] = {
            name = "advancedrifle_extendedclip",
            price = 1500,
            amount = 50,
			info = {},
            type = "item",
			slot = 31,
        },
        [32] = {
            name = "rifle_flashlight",
            price = 1000,
            amount = 50,
			info = {},
            type = "item",
			slot = 32,
        },
        [33] = {
            name = "combatpdw_scope",
            price = 500,
            amount = 50,
			info = {},
            type = "item",
			slot = 33,
        },
        [34] = {
            name = "rifle_grip",
            price = 500,
            amount = 50,
			info = {},
            type = "item",
			slot = 34,
        },
        [35] = {
            name = "security_card_01",
            price = 10500,
            amount = 50,
			info = {},
            type = "item",
			slot = 35,
        },
        [36] = {
            name = "security_card_02",
            price = 10500,
            amount = 50,
			info = {},
            type = "item",
			slot = 36,
        },
    }
}

-- Job By T&Y Develompment